name: Publish Docker images

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - EMSDK_VERSION: 2.0.12
            LLVM_VERSION: 11.1.0-rc1
            platforms: linux/arm64/v8,linux/amd64
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
    - uses: docker/setup-buildx-action@v1
    - name: Login to ghcr.io
      run: echo ${GH_PACKAGES_TOKEN} | docker login -u ${GITHUB_ACTOR} --password-stdin ghcr.io
      env:
        GH_PACKAGES_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
    - name: Cache Docker layers
      uses: actions/cache@v2
      id: cache
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-${{ matrix.EMSDK_VERSION }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.EMSDK_VERSION }}-buildx-
    - name: Build LLVM base image
      run: >
        docker buildx build
        --cache-from "type=local,src=/tmp/.buildx-cache"
        --cache-to "type=local,dest=/tmp/.buildx-cache"
        --build-arg EMSDK_VERSION=${{ matrix.EMSDK_VERSION }}
        --build-arg LLVM_VERSION=${{ matrix.LLVM_VERSION }}
        --platform ${{ matrix.platforms }}
        --tag ghcr.io/rickardp/emscripten-devcontainer:${{ matrix.EMSDK_VERSION }}
        --push
        .
