name: Publish Docker images

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-llvm:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - EMSDK_VERSION: 2.0.12
            LLVM_VERSION: 11.1.0-rc1
            platforms: linux/arm64/v8,linux/amd64
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
    - uses: docker/setup-buildx-action@v1
    - name: Login to ghcr.io
      run: echo ${GH_PACKAGES_TOKEN} | docker login -u ${GITHUB_ACTOR} --password-stdin ghcr.io
      env:
        GH_PACKAGES_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
    - name: Pull last build image
      run: >
        docker pull ghcr.io/rickardp/emscripten-devcontainer-buildcache:llvm-${{ matrix.LLVM_VERSION }} || true
    - name: Build LLVM base image
      run: >
        docker buildx build
        --build-arg LLVM_VERSION=${{ matrix.LLVM_VERSION }}
        --platform ${{ matrix.platforms }}
        --cache-from ghcr.io/rickardp/emscripten-devcontainer-buildcache:llvm-${{ matrix.LLVM_VERSION }}
        --tag ghcr.io/rickardp/emscripten-devcontainer-buildcache:llvm-${{ matrix.LLVM_VERSION }}
        --target llvm_base
        --push
        .
